--- 
title: "Tp Bookdown"
author: "Aurélien EBERSOLD"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

```{r}
library(flexdashboard)
library(tidyverse)
library(readxl)
library(lubridate)
setwd("~/cours cefim/R_cours/TP/bookdown/TP_bookdown")
energy_main<-read_delim("owid-energy-data__OWID.csv")
production_main<-read_delim("Production_Crops_Livestock_E_All_Data.csv")
population_main<-read_excel("WPP2019_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES_UN.xlsx")

#energy
energy_clean<-energy_main |> 
  select(1:3,ends_with("consumption")) |> 
  pivot_longer(cols = 4:16,
               names_to = 'energy',
               values_to = 'consumption') |> 
  filter(year>=1960) |>  
  mutate(year=as_factor(year)) |> 
  
  
  mutate(type=case_when(energy=="biofuel_consumption"~"type_energie",
                        energy=="solar_consumption"~"energie",
                        energy=="wind_consumption"~"energie",
                        energy=="renewables_consumption"~"type_energie",
                        energy=="other_renewable_consumption"~"type_energie",
                        energy=="hydro_consumption"~"energie",
                        energy=="coal_consumption"~"energie",
                        energy=="nuclear_consumption"~"energie",
                        energy=="primary_energy_consumption"~"type_energie",
                        energy=="oil_consumption"~"energie",
                        energy=="fossil_fuel_consumption"~"type_energie",
                        energy=="gas_consumption"~"energie",
                        energy=="low_carbon_consumption"~"type_energie",
                        
                        )) |> 
  mutate(energy=substr(energy,1,nchar(energy)-12)) |> 
  mutate(year=year(as.Date(year, format = "%Y"))) 

#population  
population_clean<-population_main |> 
  pivot_longer(cols=8:78,
               names_to="annee",
               values_to = 'valeurs') |> 
  filter(Type=="Country/Area") |> 
  filter(annee>=1960) |> 
  mutate(annee=year(as.Date(annee, format = "%Y"))) |> 
  mutate(valeurs=as.double(valeurs)) |>
  mutate(valeurs=valeurs*1000)

#production
production_F<-production_main |> 
  select(1:7,ends_with("F")) |> 
  pivot_longer(cols = 8:67,
               names_to='annee',
               values_to="F") |> 
  mutate(annee=substr(annee,2,5 ))

production_Y<-production_main |> 
  select(-ends_with("F")) |>
   pivot_longer(cols = 8:67,
               names_to='annee',
               values_to="valeurs") |> 
  mutate(annee=substr(annee,2,5 ))

production_clean<-production_F |> 
  left_join(production_Y) |> 
  filter(grepl("Total",Item)) |> 
  mutate(Item=substr(Item,1,nchar(Item)-7)) |> 
  mutate(annee=year(as.Date(annee, format = "%Y")))
```

```{r }


#energy
energy_clean<-energy_main |> 
  select(1:3,ends_with("consumption")) |> 
  pivot_longer(cols = 4:16,
               names_to = 'energy',
               values_to = 'consumption') |> 
  filter(year>=1960) |>  
  mutate(year=as_factor(year)) |> 
  
  
  mutate(type=case_when(energy=="biofuel_consumption"~"type_energie",
                        energy=="solar_consumption"~"energie",
                        energy=="wind_consumption"~"energie",
                        energy=="renewables_consumption"~"type_energie",
                        energy=="other_renewable_consumption"~"type_energie",
                        energy=="hydro_consumption"~"energie",
                        energy=="coal_consumption"~"energie",
                        energy=="nuclear_consumption"~"energie",
                        energy=="primary_energy_consumption"~"type_energie",
                        energy=="oil_consumption"~"energie",
                        energy=="fossil_fuel_consumption"~"type_energie",
                        energy=="gas_consumption"~"energie",
                        energy=="low_carbon_consumption"~"type_energie",
                        
                        )) |> 
  mutate(energy=substr(energy,1,nchar(energy)-12)) |> 
  mutate(year=year(as.Date(year, format = "%Y"))) 

#population  
population_clean_cont<-population_main |> 
  pivot_longer(cols=8:78,
               names_to="annee",
               values_to = 'valeurs') |> 
  filter(Type=="Region") |> 
  filter(annee>=1960) |> 
  mutate(annee=year(as.Date(annee, format = "%Y"))) |> 
  mutate(valeurs=as.double(valeurs)) |> 
  mutate(valeurs=valeurs*1000) |> 
  rename(name=3)

#production
production_F<-production_main |> 
  select(1:7,ends_with("F")) |> 
  pivot_longer(cols = 8:67,
               names_to='annee',
               values_to="F") |> 
  mutate(annee=substr(annee,2,5 ))

production_Y<-production_main |> 
  select(-ends_with("F")) |>
   pivot_longer(cols = 8:67,
               names_to='annee',
               values_to="valeurs") |> 
  mutate(annee=substr(annee,2,5 ))

production_clean<-production_F |> 
  left_join(production_Y) |> 
  filter(grepl("Total",Item)) |> 
  mutate(Item=substr(Item,1,nchar(Item)-7)) |> 
  mutate(annee=year(as.Date(annee, format = "%Y")))


codepays<-read_csv("code_pays.csv") 
  
production_cont<-production_clean |>
 
  inner_join(codepays ,by=c("Area"="name")) |> 
  group_by(annee,region)

energy_cont<-energy_clean |> 
  inner_join(codepays ,by=c("country"="name"))


```



# Vue mondiale

Chart production par année
-----------------------------------------------------------------------



```{r}
ggplot(production_clean)+
  aes(annee,valeurs,fill=Item)+
  geom_col()
```

##Chart population par année

```{r}
ggplot(population_clean )+
  aes(annee,valeurs)+
  
  geom_col()
```

Chart energie matiere
-----------------------------------------------------------------------



```{r}
ggplot(energy_clean |> filter(type=="energie"))+
  aes(year,consumption,fill=energy)+
  geom_col()
```

##Chart type d'energie

```{r}
ggplot(energy_clean |> filter(type=="type_energie"))+
  aes(year,consumption,fill=energy)+
  geom_col()
```


# Vue Continentale


Chart production par année et par continent
-----------------------------------------------------------------------



```{r}
ggplot(production_cont)+
  aes(annee,valeurs,fill=Item)+
  facet_grid(~region)+
  geom_col()
```

##Chart population par année et par continent

```{r}
ggplot(population_clean_cont)+
  aes(annee,valeurs,fill=name)+
  geom_col()
```

Chart energie matiere
-----------------------------------------------------------------------



```{r}
ggplot(energy_cont |> filter(type=="energie"))+
  aes(year,consumption,fill=energy)+
  facet_grid(~region)+
  geom_col()
```

##Chart type d'energie

```{r}
ggplot(energy_cont |> filter(type=="type_energie"))+
  aes(year,consumption,fill=energy)+
  facet_grid(~region)+
  geom_col()
```